java_binary(
    name = "servlet",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//appengine:javax.servlet.api",
        "//jars",
        "@com_google_appengine_java//:api",
    ],
)
