load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_template_library")

closure_js_template_library(
    name = "soy",
    srcs = ["vicarious.soy"],
    visibility = ["//visibility:public"],
)
