java_import(
  name = "jars",
  jars = [
    "aopalliance.jar",
    "javax-inject.jar",
    "org.json.jar",
    "gson-2.2.2.jar",
    "guava-19.0.jar",
    "guice-4.0.jar",
    "guice-servlet-4.0.jar",
  ],
  visibility = ["//visibility:public"],
)
